[tool.poetry]
name = "aiko_services"
version = "0.3"
description = "Distributed embedded service framework"
authors = ["Andy Gelme <geekscape@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10.0"
asciimatics = "^1.14.0"
avro = "^1.11.1"
avro-validator = "^1.2.1"
click = "^8.0"
numpy = "^1.19.1"
opencv-python = { version = "^4.4.0", optional = true }
paho-mqtt = ">=1.6.1,<2.0.0"
Pillow = "^9.0.0"
PyAudio = { version = "^0.2.13", optional = true }
pyperclip = "^1.8.2"
requests = "^2.25.1"
transitions = "^0.9.0"
wrapt = "^1.12.1"

[tool.poetry.extras]
linux = ["PyAudio"]
macosx = ["PyAudio"]
opencv = ["opencv-python"]

[tool.poetry.scripts]
aiko = "aiko_services.cli:main"
aiko_dashboard = "aiko_services.dashboard:main"
aiko_pipeline = "aiko_services.pipeline:main"
aiko_registrar = "aiko_services.registrar:main"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
ipython = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.core.masonry.api"
